package domain

// This file is automatically generated by the domain package.
// It exports all public types and functions for easy importing.

// Export all enum types
type (
	// Project types
	ProjectType = domain.ProjectType
	// Platforms
	Platform = domain.Platform
	// Architectures
	Architecture = domain.Architecture
	// Git providers
	GitProvider = domain.GitProvider
	// Docker registries
	DockerRegistry = domain.DockerRegistry
	// Action triggers
	ActionTrigger = domain.ActionTrigger
	// Configuration states
	ConfigState = domain.ConfigState
)

// Export all constants
const (
	// Project types
	ProjectTypeCLI     = domain.ProjectTypeCLI
	ProjectTypeWeb     = domain.ProjectTypeWeb
	ProjectTypeLibrary = domain.ProjectTypeLibrary
	ProjectTypeAPI     = domain.ProjectTypeAPI
	ProjectTypeDesktop = domain.ProjectTypeDesktop

	// Platforms
	PlatformLinux   = domain.PlatformLinux
	PlatformDarwin  = domain.PlatformDarwin
	PlatformWindows = domain.PlatformWindows
	PlatformFreeBSD = domain.PlatformFreeBSD
	PlatformOpenBSD = domain.PlatformOpenBSD
	PlatformNetBSD  = domain.PlatformNetBSD

	// Architectures
	ArchitectureAMD64   = domain.ArchitectureAMD64
	ArchitectureARM64   = domain.ArchitectureARM64
	Architecture386     = domain.Architecture386
	ArchitectureARM     = domain.ArchitectureARM
	ArchitecturePPC64   = domain.ArchitecturePPC64
	ArchitecturePPC64LE = domain.ArchitecturePPC64LE
	ArchitectureS390X   = domain.ArchitectureS390X
	ArchitectureMIPS    = domain.ArchitectureMIPS
	ArchitectureMIPSLE  = domain.ArchitectureMIPSLE

	// Git providers
	GitProviderGitHub     = domain.GitProviderGitHub
	GitProviderGitLab     = domain.GitProviderGitLab
	GitProviderBitbucket  = domain.GitProviderBitbucket
	GitProviderGitea      = domain.GitProviderGitea
	GitProviderSelfHosted = domain.GitProviderSelfHosted

	// Docker registries
	DockerRegistryDockerHub = domain.DockerRegistryDockerHub
	DockerRegistryGitHub    = domain.DockerRegistryGitHub
	DockerRegistryGitLab    = domain.DockerRegistryGitLab
	DockerRegistryQuay      = domain.DockerRegistryQuay
	DockerRegistryCustom    = domain.DockerRegistryCustom

	// Action triggers
	ActionTriggerVersionTags = domain.ActionTriggerVersionTags
	ActionTriggerAllTags     = domain.ActionTriggerAllTags
	ActionTriggerManual      = domain.ActionTriggerManual
	ActionTriggerMain        = domain.ActionTriggerMain
	ActionTriggerRelease     = domain.ActionTriggerRelease

	// Configuration states
	ConfigStateDraft      = domain.ConfigStateDraft
	ConfigStateValid      = domain.ConfigStateValid
	ConfigStateInvalid    = domain.ConfigStateInvalid
	ConfigStateProcessing = domain.ConfigStateProcessing
	ConfigStateGenerated  = domain.ConfigStateGenerated
)

// Export configuration types
type (
	// Build tag
	BuildTag = domain.BuildTag
	// Safe project configuration
	SafeProjectConfig = domain.SafeProjectConfig
)

// Export all validation functions
var (
	ValidateProjectName        = domain.ValidateProjectName
	ValidateBinaryName         = domain.ValidateBinaryName
	ValidateMainPath          = domain.ValidateMainPath
	ValidateProjectDescription  = domain.ValidateProjectDescription
	ValidatePlatforms          = domain.ValidatePlatforms
	ValidateArchitectures      = domain.ValidateArchitectures
	ValidatePlatformArchCompatibility = domain.ValidatePlatformArchCompatibility
	ValidateGitProvider        = domain.ValidateGitProvider
	ValidateDockerRegistry    = domain.ValidateDockerRegistry
	ValidateDockerRegistryURL  = domain.ValidateDockerRegistryURL
	ValidateDockerImageName    = domain.ValidateDockerImageName
	ValidateActionTriggers     = domain.ValidateActionTriggers
	ValidateBuildTag           = domain.ValidateBuildTag
	ValidateBuildTags          = domain.ValidateBuildTags
	ValidateConfigState        = domain.ValidateConfigState
)

// Export utility functions
var (
	// Enum utility functions
	GetRecommendedArchitectures = domain.GetRecommendedArchitectures
	GetAllArchitectures       = domain.GetAllArchitectures
	GetAllActionTriggers      = domain.GetAllActionTriggers
	GetRecommendedTriggers     = domain.GetRecommendedTriggers
	GenerateGitHubActionsTriggersYAML = domain.GenerateGitHubActionsTriggersYAML
	GetCommonBuildTags        = domain.GetCommonBuildTags
	FilterBuildTagsByPlatform = domain.FilterBuildTagsByPlatform
	
	// Build tag functions
	CreateBuildTag = domain.CreateBuildTag
	
	// Configuration state functions
	GetInitialConfigState = domain.GetInitialConfigState
	GetAllConfigStates     = domain.GetAllConfigStates
	
	// Configuration constructor
	NewSafeProjectConfig = domain.NewSafeProjectConfig
)

// Package info
const (
	// Version information
	PackageVersion = "1.0.0"
	PackageName    = "domain"
	
	// TypeSpec compatibility
	TypeSpecVersion = "latest"
	GeneratedAt     = "2025-11-16"
)